# Generated by Django 3.2.12 on 2022-08-05 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_descrption_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='descrption',
            new_name='description',
        ),
    ]
